[project]
name = "react-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=25.9.0",
    "langchain>=1.0.2",
    "langchain-openai>=1.0.1",
    "python-dotenv>=1.2.1",
]
